export const selectCategory = [
  {
    id: "1",
    name: "Vegetables",
    image: "/assets/images/vegetables.png",
    totalItems: 23,
    bgColor: "#E9E0FD",
  },
  {
    id: "2",
    name: "Fruits",
    image: "/assets/images/fruits.png",
    totalItems: 18,
    bgColor: "#D8FFF8",
  },
  {
    id: "3",
    name: "Coffee & Tea",
    image: "/assets/images/coffee.png",
    totalItems: 12,
    bgColor: "#FFD8F4",
  },
  {
    id: "4",
    name: "Cleaning & Ess.",
    image: "/assets/images/cleaning.png",
    totalItems: 25,
    bgColor: "#F2FCB6",
  },
  {
    id: "5",
    name: "Beverage",
    image: "/assets/images/soda.png",
    totalItems: 15,
    bgColor: "#FCB6B6",
  },
  {
    id: "6",
    name: "Bakery Products",
    image: "/assets/images/wings.png",
    totalItems: 36,
    bgColor: "#B7FCB6",
  },
];

export const popularProducts = [
  {
    id: "1",
    name: "Broccoli",
    image: "/assets/images/broccoli.png",
    price: "$ 25.00 / KG",
    rating: "4.5",
    totalReviews: "(102 Review)",
  },
  {
    id: "2",
    name: "Tomato",
    image: "/assets/images/tomato.png",
    price: "$ 20.00 / KG",
    rating: "4.5",
    totalReviews: "(102 Review)",
  },
  {
    id: "3",
    name: "Milk Bottle",
    image: "/assets/images/group-milk-bottle.png",
    price: "$ 54.00 / KG",
    rating: "4.5",
    totalReviews: "(102 Review)",
  },
  {
    id: "4",
    name: "Mountain Dew Pck",
    image: "/assets/images/mountain-dew.png",
    price: "$ 25.00 / KG",
    rating: "4.5",
    totalReviews: "(102 Review)",
  },
  {
    id: "5",
    name: "Chakki Wheat Atta",
    image: "/assets/images/chakki.png",
    price: "$ 25.00 / KG",
    rating: "4.5",
    totalReviews: "(102 Review)",
  },
  {
    id: "6",
    name: "Jimari-Chass-Masala",
    image: "/assets/images/jimari.png",
    price: "$ 25.00 / KG",
    rating: "4.5",
    totalReviews: "(102 Review)",
  },
  {
    id: "7",
    name: "Jim Jams",
    image: "/assets/images/jim-jams.png",
    price: "$ 25.00 / KG",
    rating: "4.5",
    totalReviews: "(102 Review)",
  },
  {
    id: "8",
    name: "Basmati Rice",
    image: "/assets/images/basmati.png",
    price: "$ 25.00 / KG",
    rating: "4.5",
    totalReviews: "(102 Review)",
  },
];